data = [{'name' : 'Mr beast',
         'age' : 27,
         'insta' : 124,
         'country' : 'USA'}, 
         {'name': 'Jake Paul',
         'age' : 26,
         'insta' : 190,
         'country' : 'USA'},
         {'name' : 'Jeffree Star',
         'age' : 35,
         'insta' : 200,
         'country' : 'USA'},
         {'name' : 'Sakira',
          'age' : 46,
          'insta' : 300,
          'country' : 'Colombia'},
          {'name' : 'Zandaya',
          'age' : 29,
          'insta' : 400,
          'country' : 'California'}
          ]